#!/usr/bin/env python2

import rospy
from setpoint_publisher.republish_tf2topic import RepublishTF2Topic

if __name__ == '__main__':

    rospy.init_node('republish_tf2topic', log_level=rospy.DEBUG, disable_signals=True)
    republisher = RepublishTF2Topic()
    republisher.run()