#!/usr/bin/env python2

import rospy
from setpoint_publisher.setpoint_publisher import SetpointPublisher

if __name__ == '__main__':

    rospy.init_node('setpoint_publisher', log_level=rospy.DEBUG)
    setpoint_publisher = SetpointPublisher()
    setpoint_publisher.run()